\begin{acotado}#snippet
\end{acotado}
\acotar{arg1}#snippet
\begin{habla}#snippet
\end{habla}
\begin{parla}[arg1]{arg2}#snippet
\end{parla}
\begin{parla}{arg1}#snippet
\end{parla}
\cont#snippet
\personaje{arg1}#snippet
\fintexto#snippet
\fintexto[arg1]#snippet
\Dotfill#snippet
\sep#snippet
\pegado#snippet
\begin{versodo}#snippet
\end{versodo}
\begin{versomio}#snippet
\end{versomio}
\begin{versomiodo}#snippet
\end{versomiodo}
\estrofa#snippet